sudo: required

language: node_js
node_js:
  - "6.2.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

install:
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update
  - gem update fastlane --no-ri --no-rdoc --no-document

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xvf android-sdk_r24.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

script:
  - npm run env:linux -- staging
  - npm run test-coverage

after_success:
  - npm run codecov
  - scripts/deploy-beta.sh